version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgress_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vakhaboff
      POSTGRES_DB: shaxboz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shaxboz"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
